 # Create the new instance template
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: create-instance-template
  args:
    - compute
    - instance-templates
    - create-with-container
    - cloud-build-instance-template-v2-$_ENV-$SHORT_SHA
    - --custom-cpu=1
    - --custom-memory=2GB
    - --boot-disk-size=20GB
    - --region=us-central1
    - --subnet=new-default
    - --tags=allow-hc-and-proxy,allow-ssh
    - --container-image
    - us.gcr.io/moonlit-sphinx-394612/html-repo/nginx-image:latest
    
 # Update the managed instance group
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c','gcloud compute instance-groups managed rolling-action start-update cloudbuild-mig --version=template=cloud-build-instance-template-v2-$_ENV-$SHORT_SHA --region=us-central1 --max-unavailable=0'] 
  
- name: 'gcr.io/cloud-builders/gcloud'
  id: create-target-pool
  args:
    - compute
    - target-pools
    - create
    - my-target-pool
    - --region=us-central1
    - --http-health-check=mig-http
    - --session-affinity=NONE


- name: 'gcr.io/cloud-builders/gcloud'
  id: add-instances-to-target-pool
  args:
    - compute
    - instance-groups
    - managed
    - set-target-pools
    - cloudbuild-mig	
    - --target-pools=my-target-pool
    - --zone=us-central1-a

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-forwarding-rule
  args:
    - compute
    - forwarding-rules
    - create
    - my-forwarding-rule
    - --region=us-central1
    - --target-pool=my-target-pool
    - --ports=80
options:
 logging: CLOUD_LOGGING_ONLY